### ISSUE TITLE
Hello, after installed package error and iam not understand.

### ISSUE THREAD

**Issue by rizkijanuarr** [tomatophp/filament-api#3]
![filapi](https://github.com/user-attachments/assets/1ea1f0e2-4c59-4997-9ab9-9fb09a20cce4)

Hello I am having problems after installing this package, does anyone know why? I have tried it repeatedly but it still fails. Maybe someone has experienced the same thing, thank you in advance!

**Comment by 3x1io** [comment]
please use SQLite3 Driver to make this work!
